/**
 * Registry serialization — the write side of the reconciler
 * (`docs/12-architecture.md §12.4`).
 *
 * The reconciler reads each use case's `README.md` (truth) and writes the
 * registry index (cache). This module renders typed rows back into the
 * `registry/index.md` table so a parse→serialize round-trip is stable. The
 * network/Git side (M3) calls this; the rendering is pure and testable now.
 */

import type { RegistryRow } from "./registry.js";

const COLUMNS = [
  "ID",
  "Title",
  "Stage",
  "Lane",
  "Status",
  "Plant",
  "Domain",
  "Level",
  "Heat",
  "Sponsor",
  "Value (proj)",
  "Value (real)",
  "Since",
] as const;

function cell(value: string | number | undefined): string {
  if (value === undefined || value === "") return "—";
  return String(value);
}

function rowToCells(row: RegistryRow): string[] {
  return [
    cell(row.id),
    cell(row.title),
    cell(row.stage),
    cell(row.lane),
    cell(row.status),
    cell(row.plant),
    cell(row.domain),
    cell(row.level),
    cell(row.heat),
    cell(row.sponsor),
    cell(row.valueProjected),
    cell(row.valueRealized),
    cell(row.since),
  ];
}

/** Render rows to the `registry/index.md` document. `lastSync` is an ISO string. */
export function serializeRegistryIndex(rows: readonly RegistryRow[], lastSync: string): string {
  const header = `| ${COLUMNS.join(" | ")} |`;
  const separator = `|${COLUMNS.map(() => "---").join("|")}|`;
  const body = rows.map((r) => `| ${rowToCells(r).join(" | ")} |`);

  const lines = [
    "# Portfolio registry",
    "",
    "Generated by the reconciler. Do not edit by hand — changes are overwritten.",
    "",
    `Last sync: ${lastSync}`,
    "",
    header,
    separator,
    ...body,
  ];
  if (rows.length === 0) {
    lines.push("");
    lines.push("_No use cases yet. Describe a problem to get started._");
  }
  return lines.join("\n") + "\n";
}

/** Whether a freshly-read row differs from the cached row (drives reconcile writes). */
export function rowChanged(cached: RegistryRow | undefined, fresh: RegistryRow): boolean {
  if (!cached) return true;
  return JSON.stringify(cached) !== JSON.stringify(fresh);
}
